### PR TITLE
Support function space

### PR DESCRIPTION
**Pull request by KevinyhZou**
### Changelog category (leave one):
- New Feature
Support function space

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

``` sql
SELECT space(3);
```

Result:

``` text
┌─space(3) ────┐
│              │
└──────────────┘
```

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by KevinyhZou** [comment]
the releated issue is: https://github.com/Kyligence/ClickHouse/issues/320

**Comment by liuneng1994** [comment]
test this please

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Comment by liuneng1994** [comment]
@KevinyhZou please resolve conflicts

**Comment by KevinyhZou** [comment]
> @KevinyhZou please resolve conflicts

done @liuneng1994

**Comment by liuneng1994** [comment]
test this please

**Pull request merged**
