### PR TITLE
[CH-184] support prewhere

### PR DESCRIPTION
**Pull request by liuneng1994**
Changelog category (leave one):
- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
support prewhere on mergetree

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by liuneng1994** [comment]
test this please with 496

**Comment by liuneng1994** [comment]
test this please with 496

**Comment by liuneng1994** [comment]
test this please with 496

**Comment by liuneng1994** [comment]
test this please with 496

**Comment by liuneng1994** [comment]
test this please with 496

**Comment by liuneng1994** [comment]
test this please with 496

**Comment by liuneng1994** [comment]
test this please with 496

**Pull request merged**
