### PR TITLE
[GLUTEN-2463][CH] Allow nullable tuple column as input in Nested::flatten

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
close issues: https://github.com/oap-project/gluten/issues/2463 and https://github.com/oap-project/gluten/issues/2459

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lgbo-ustc** [comment]
It looks like `BlockUtil::flattenBlock` becomes the same as 'NestedUtil::flatten'. May replace `BlockUtil::flattenBlock`

**Comment by taiyang-li** [comment]
```
$ ./build_gcc/utils/extern-local-engine/tests/unit_tests_local_engine  --gtest_filter="NestedUtils.*" --gtest_catch_exceptions=0         2>&1 | tee run.log      
2023-07-26 15:15:54.787 <Warning> SignalHandler: LD_PRELOAD is not set, SignalHandler is disabled
Note: Google Test filter = NestedUtils.*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from NestedUtils
[ RUN      ] NestedUtils.flatten
[       OK ] NestedUtils.flatten (0 ms)
[----------] 1 test from NestedUtils (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.

```

**Comment by lgbo-ustc** [comment]
LGTM

**Pull request merged**
