### PR TITLE
[CH-290] support to_date/date_format/trunc/add_months/map_from_arrays/translate

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
part1: support function add_months/translate

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
Notice: must be merge until clickhouse upgrade to 23.2

**Comment by taiyang-li** [comment]
test this please with 951

**Comment by taiyang-li** [comment]
test this please with 951

**Comment by taiyang-li** [comment]
test this please with 951

**Comment by taiyang-li** [comment]
test this please with 951

**Comment by taiyang-li** [comment]
test this please with 951

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
