### PR TITLE
fixed : cover more jni interfaces for catching c++ exceptions

### PR DESCRIPTION
**Pull request by lgbo-ustc**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by zzcclp** [comment]
test this please

**Comment by zzcclp** [comment]
retest this please

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
