### PR TITLE
[CH-210] Support trim expression.

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support trim expression.

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
test this please

**Comment by taiyang-li** [comment]
test this please

**Comment by taiyang-li** [comment]
test this please

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
