### PR TITLE
[CH-300] fix multi aggregation fail due to serialize partial aggregation to aggregation in shuffle

### PR DESCRIPTION
**Pull request by shuai-xu**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix the bug that multi aggregation fail due to mistake serializing partial aggregation with aggregation in shuffle

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by shuai-xu** [comment]
@binmahone can you help to review this change?

**Comment by liuneng1994** [comment]
test this please

**Pull request merged**
