### PR TITLE
[CH-278] Fix failed uts of lpad/rpad in https://github.com/oap-project/gluten/pull/917

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix failed uts of lpad/rpad in https://github.com/oap-project/gluten/pull/917

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
test this please with 917

**Comment by taiyang-li** [comment]
test this please with 917

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
