### PR TITLE
[CH-278] part1: support function md5/lpad/rpad/reverse

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
part1: support function md5/lpad/rpad/reverse

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
test this please with 917

**Comment by taiyang-li** [comment]
test this please with 917

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
