### PR TITLE
Fixed a bug which may cause coredump

### PR DESCRIPTION
**Pull request by lgbo-ustc**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable or prestable release)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

The row argument is required to be a reference, we cannot pass a right value variable here

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lgbo-ustc** [comment]
test this please

**Comment by liuneng1994** [comment]
test this please

**Comment by lgbo-ustc** [comment]
test this please

**Pull request closed without merging**
