### PR TITLE
[VL-1004]Upgrade substrait proto by velox

### PR DESCRIPTION
**Pull request by loneylee**
### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Upgrade substrait proto by velox.

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/
test by glutenut

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by zzcclp** [comment]
test this please with 1004

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Comment by zzcclp** [comment]
test this please with 1004

**Pull request merged**
