### PR TITLE
[CH-212] support map[key] and array[index] expression && solve map/array nullable compatiability issue

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- support map[key] and array[index] expression
- some compatiable changes to make sure transforming from substrait map/array functions to ch working.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
test this please with 609

**Comment by taiyang-li** [comment]
Waiting for https://github.com/oap-project/gluten/pull/574 to be merged.

**Comment by taiyang-li** [comment]
test this please with 609

**Comment by taiyang-li** [comment]
test this please with 609

**Comment by taiyang-li** [comment]
test this please with 609

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
