### PR TITLE
[CH-426]fix null partition read

### PR DESCRIPTION
**Pull request by lhuang09287750**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix partition column read for null value

### Documentation entry for user-facing changes
Spark+ch backend will read the null partition column as the default value of partition column type and
this behavior is differrent from spark which will read the null just as null.
So this pr add a fix to process null partition column read problem.

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lhuang09287750** [comment]
https://github.com/Kyligence/ClickHouse/issues/426

**Comment by lhuang09287750** [comment]
@liuneng1994 CI still in problem?

**Comment by lhuang09287750** [comment]
@liuneng1994 CI still in problem?

**Pull request closed without merging**
