### PR TITLE
[fixed #142]catch java exception in c++

### LINKED ISSUE #142: Java exceptions are not catched in C++
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
When we try to call a java method from C++, an exception could happen in the java code. But it is not handled in C++ code, and cause a coredump or unexpected behaviors.

**How to reproduce**
gluten commit:30d2f4d5a3ab13a4f212341691265fac0afc852d
clickhouse commit: d6a6cc97350081eecd62aabe1060b19a405fbe3f

run the  following query
```SQL
select count(*) from (select * from parquet.`/github/gluten-docker/packages/parquet_demo` as l1 left join  parquet.`/github/gluten-docker/packages/parquet_demo` as l2 on l1.id = l2.id limit 1) as t;
```
It will generate a empty block and cause an exception here in CHExecUtil.scala
```Java

          case SinglePartition =>
            rdd.mapPartitionsWithIndexInternal(
              (_, cbIter) => {
                options.setPartitionNum(1)
                options.setName("rr")
                val iter = new Iterator[Product2[Int, ColumnarBatch]] with AutoCloseable {
                  val splitIterator = new BlockSplitIterator(
                    cbIter
                      .map(
                        cb =>
                          CHNativeBlock
                            .fromColumnarBatch(cb)
                            .orElseThrow(() =>
                              new IllegalStateException("unsupported columnar batch"))
                            .blockAddress()
                            .asInstanceOf[java.lang.Long])
                      .asJava,
                    options)

```

**Expected behavior**
catch the java exceptions in c++.

**Error message and/or stacktrace**

**Additional context**

### PR DESCRIPTION
**Pull request by lgbo-ustc**
Changelog category (leave one):

- Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

related to issue #142

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by liuneng1994** [comment]
test this please

**Comment by liuneng1994** [comment]
test this please

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
