### PR TITLE
[250] Support grouping sets

### PR DESCRIPTION
**Pull request by lgbo-ustc**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...
Offload `CustomExpand ` into `ClickHouse` to support grouping sets.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lgbo-ustc** [comment]
Performance compared with vanilla spark.

#### vanilla spark
```
+----------+-------+-----------+
| msgtype  | hour  | count(1)  |
+----------+-------+-----------+
| NULL     | NULL  | 34749458  |
| NULL     | 0     | 16773019  |
| NULL     | 1     | 17976439  |
| 14       | NULL  | 16629906  |
| 14       | 0     | 7198255   |
| 14       | 1     | 9431651   |
| 208      | NULL  | 18119552  |
| 208      | 0     | 9574764   |
| 208      | 1     | 8544788   |
+----------+-------+-----------+
9 rows selected (4.092 seconds)

```

#### gluten
```
+----------+-------+-----------+
| msgtype  | hour  | count(1)  |
+----------+-------+-----------+
| NULL     | NULL  | 34749458  |
| NULL     | 0     | 16773019  |
| NULL     | 1     | 17976439  |
| 14       | NULL  | 16629906  |
| 14       | 0     | 7198255   |
| 14       | 1     | 9431651   |
| 208      | NULL  | 18119552  |
| 208      | 0     | 9574764   |
| 208      | 1     | 8544788   |
+----------+-------+-----------+
9 rows selected (7.674 seconds)
```

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Comment by lgbo-ustc** [comment]
close https://github.com/Kyligence/ClickHouse/issues/250

**Pull request merged**
