### PR TITLE
[Gluten-898]Update substrait proto

### PR DESCRIPTION
**Pull request by loneylee**
Changelog category (leave one):
- New Feature
Update substrait proto by velox

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/
test this please with 898

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by zzcclp** [comment]
test this please with 898

**Comment by loneylee** [comment]
test this please with 898

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
