### PR TITLE
[CH-259]fixed a bug related to count(1)/count(*)

### PR DESCRIPTION
**Pull request by lgbo-ustc**
Changelog category (leave one):
- Bug Fix (user-visible misbehaviour in official stable)

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

Closes https://github.com/Kyligence/ClickHouse/issues/259.

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lgbo-ustc** [comment]
please test this with 831

**Comment by lgbo-ustc** [comment]
test this please with 831

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
