### PR TITLE
[CH-294] support collect_list

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
support aggregate function collect_list

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
test this please with 966

**Comment by taiyang-li** [comment]
test this please with 966

**Comment by taiyang-li** [comment]
test this please with 966

**Comment by taiyang-li** [comment]
test this please with 966

**Comment by taiyang-li** [comment]
test this please with 966

**Comment by taiyang-li** [comment]
test this please with 966

**Comment by taiyang-li** [comment]
test this please with 966

**Comment by taiyang-li** [comment]
test this please with 966

**Comment by taiyang-li** [comment]
TPCH q20 failed, and it is a known issue not related to this pr.

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
