### PR TITLE
[CH-397] support posexplode/sequence functions

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
I check-pick prs from CH because posexplode/sequence/mapFromArrays functions need them:
- https://github.com/ClickHouse/ClickHouse/pull/31125
- https://github.com/ClickHouse/ClickHouse/pull/46940
- https://github.com/ClickHouse/ClickHouse/pull/48207 

This pr also fix https://github.com/Kyligence/ClickHouse/issues/410

### CODE REVIEW

**Comment by taiyang-li** [comment]
test this please with 1281

**Comment by taiyang-li** [comment]
test this please with 1281

**Comment by taiyang-li** [comment]
performance tests
```
select count(1) from (select l_orderkey, posexplode(array('1', '2')), l_suppkey from lineitem)  ;

set spark.gluten.sql.columnar.generate=true;
1 row selected (0.227 seconds) 

set spark.gluten.sql.columnar.generate=false;
1 row selected (1.106 seconds)
```

**Comment by taiyang-li** [comment]
test this please with 1281

**Comment by taiyang-li** [comment]
test this please with 1281

**Comment by taiyang-li** [comment]
test this please with 1281

**Comment by taiyang-li** [comment]
test this please with 1281

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
