### PR TITLE
[CH-349]fix substrait parser to support some singular_or_list cases

### PR DESCRIPTION
**Pull request by lhuang09287750**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
fix substrait parser for the case when filter condition has only one singular_or_list

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by liuneng1994** [comment]
测试代码有吗

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lhuang09287750** [comment]
@liuneng1994 
https://github.com/Kyligence/ClickHouse/issues/349

test("range demo1 spark codegen true") {

    withSQLConf(("spark.sql.codegen.wholeStage", "true")) {
      val start = java.lang.Long.MAX_VALUE - 3
      val end = java.lang.Long.MIN_VALUE + 2
      val length = spark.range(start, end, 1).collect.length
      // scalastyle:off println
      println(length)
      // scalastyle:on println


    }

  // Thread.sleep(600000)

}

**Comment by lhuang09287750** [comment]
@liuneng1994 
https://github.com/Kyligence/ClickHouse/issues/349

  test("demo1") {
      withTempView("product_defect_index_scrum") {
        Seq(("asofdate", 1.0d, "ring", "scrum_team"))
          .toDF("asofdate", "index_score_sum", "ring", "scrum_team").
          createOrReplaceTempView("product_defect_index_scrum")
        val ret = spark.sql(
          """
            |select 1 from product_defect_index_scrum where scrum_team in ('CSE','KC Offering')
            |
            |""".stripMargin)
        ret.show()
       // Thread.sleep(600000000)
      }
    }

**Review by liuneng1994 — APPROVED** [review]

**Pull request merged**
