### PR TITLE
[CH-364] Make sure global_context is initialized once at the first invoking of JNI_Onload and finalized once at exit

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

- Make sure global_context is initialized once at the first invoking  of JNI_Onload and finalized once at exit(current not).
- Make sure every correspoinding settings and configs are applied at JNI_Onload (current not).
- Some refactor works.

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by liuneng1994** [comment]
test this please with 1143

**Comment by liuneng1994** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by liuneng1994** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Comment by taiyang-li** [comment]
test this please with 1143

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
