### PR TITLE
Support loading setting from config file and improve logging.

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
- support loading settings from config file, which is defined by environment variable  `CLICKHOUSE_BACKEND_CONFIG`
- improve logging, support logging to files, and add more details in logs. Like below

```
$ grep ClickHouseBackend *                                                                                                                        
clickhouse.log:2022.09.09 15:12:36.495639 [ 11769 ] {} <Information> ClickHouseBackend: Init logger.
clickhouse.log:2022.09.09 15:12:36.512366 [ 11769 ] {} <Information> ClickHouseBackend: Init settings.
clickhouse.log:2022.09.09 15:12:36.512646 [ 11769 ] {} <Information> ClickHouseBackend: Init global context.
clickhouse.log:2022.09.09 15:12:36.530314 [ 11769 ] {} <Information> ClickHouseBackend: Register all functions.
clickhouse.log:2022.09.09 15:12:36.530345 [ 11769 ] {} <Information> ClickHouseBackend: Init compiled expressions cache factory.

```

A example of config.xml
``` xml 
<?xml version="1.0"?>
<!--
  NOTE: User and query level settings are set up in "users.xml" file.
-->
<yandex>
    <logger>
        <!-- Possible levels: https://github.com/pocoproject/poco/blob/poco-1.9.4-release/Foundation/include/Poco/Logger.h#L105 -->
        <level>trace</level>
	<log>/data1/liyang/cppproject/spark/spark-3.1.1-bin-hadoop2.7/ch/log/clickhouse.log</log>
	<errorlog>/data1/liyang/cppproject/spark/spark-3.1.1-bin-hadoop2.7/ch/log/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>10</count>
        <!-- <console>1</console> --> <!-- Default behavior is autodetection (log to console if not daemon mode and is tty) -->
    </logger>

    <local_engine>
    	<settings>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>random</load_balancing>
	    <normalize_function_names>true</normalize_function_names>
    	    <use_local_cache_for_remote_storage>0</use_local_cache_for_remote_storage>
	    <optimize_trivial_count_query>1</optimize_trivial_count_query>
	    <allow_introspection_functions>1</allow_introspection_functions>
	</settings>
    </local_engine>

    <path>/data1/liyang/cppproject/spark/spark-3.1.1-bin-hadoop2.7/ch/data</path>


    <hdfs>
	    <libhdfs3_conf>data1/liyang/cppproject/spark/spark-3.1.1-bin-hadoop2.7/ch/conf/hdfs-site.testcluster.xml</libhdfs3_conf>
    </hdfs>

</yandex>

```
> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
Does anyone have time to review this PR, thanks!

**Comment by lgbo-ustc** [comment]
Update the way to loading configuratiob.
1. if gluten provide `spark.gluten.sql.columnar.backend.ch.runtime_conf.conf_file`, use the configuration from the local file first
2. if gluten also provide other configuration starts with `spark.gluten.sql.columnar.backend.ch.runtime_conf`, we will overwrite the configurations from `spark.gluten.sql.columnar.backend.ch.runtime_conf.conf_file`

**Comment by liuneng1994** [comment]
test this please with 365

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
