### PR TITLE
[CH-202] Support condition expression, include if/else and case/when

### PR DESCRIPTION
**Pull request by taiyang-li**
### Changelog category (leave one):
- New Feature

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support condition expressions, close https://github.com/Kyligence/ClickHouse/issues/202

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
test this please with 599.

**Comment by liuneng1994** [comment]
test this please with 599

**Comment by taiyang-li** [comment]
test this please with 599

**Comment by taiyang-li** [comment]
test this please with 599

**Comment by liuneng1994** [comment]
test this please

**Comment by taiyang-li** [comment]
test this please

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
