### PR TITLE
[#156]support sort op

### PR DESCRIPTION
**Pull request by lgbo-ustc**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
support sort operator.

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lgbo-ustc** [comment]
test this please with 448

**Comment by lgbo-ustc** [comment]
test this please with 448

**Comment by lgbo-ustc** [comment]
test this please with 448

**Comment by liuneng1994** [comment]
spark的sort似乎需要支持range partition，目前还不支持这个

**Comment by lgbo-ustc** [comment]
range partition目前看起来是不支持

**Comment by liuneng1994** [comment]
test this please

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
