### PR TITLE
Improve: reducing the open operation for the same file when reading parquet files

### PR DESCRIPTION
**Pull request by lgbo-ustc**
### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Improve: reducing the open operation for the same file when reading parquet files

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lgbo-ustc** [comment]
test this please

**Comment by lgbo-ustc** [comment]
test this please

**Comment by lgbo-ustc** [comment]
test this please with 524

**Comment by lgbo-ustc** [comment]
test this please with 524

**Comment by lgbo-ustc** [comment]
test this please

**Comment by liuneng1994** [comment]
test this please

**Pull request merged**
