### PR TITLE
[CH-313] support functions position/locate

### PR DESCRIPTION
**Pull request by exmy**
related issue : [issue-313](https://github.com/Kyligence/ClickHouse/issues/313)

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by exmy** [comment]
test this please with 1020

**Comment by liuneng1994** [comment]
test this please with 1020

**Comment by liuneng1994** [comment]
test this please with 1020

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Comment by liuneng1994** [comment]
test this please with 1020

**Pull request merged**
