### PR TITLE
[398]Fixed: `groupArray`'s result could be null

### LINKED ISSUE #398: Badcase for `collect_list`
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**

```
select n_regionkey, collect_list(if(n_regionkey=0, n_name, null)) as t from nation_nullable group by n_regionkey
```
The above query will throw an exception
```
java.lang.RuntimeException: Cannot convert NULL to a non-nullable type: while converting source column `collect_list#1#Partial#collect_list` to destination column `collect_list#1#Partial#collect_list`
0. ./build1/../contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18fd05da in /data3/liangjiabiao/github/KyClickHouse/build1/utils/local-engine/libch.so
1. ./build1/../src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe481875 in /data3/liangjiabiao/github/KyClickHouse/build1/utils/local-engine/libch.so
2. ./build1/../contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception<char const (&) [43], void>(int, char const (&) [43]) @ 0xbb8abd6 in /data3/liangjiabiao/github/KyClickHouse/build1/utils/local-engine/libch.so
3. ./build1/../src/Functions/FunctionsConversion.h:3678: DB::FunctionCast<DB::CastInternalName>::prepareUnpackDictionaries(std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&) const @ 0xbc4b4fc in /data3/liangjiabiao/github/KyClickHouse/build1/utils/local-engine/libch.so
4. ./build1/../src/Functions/FunctionsConversion.h:2780: DB::FunctionCast<DB::CastInternalName>::prepare(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&) const @ 0xbc4a986 in /data3/liangjiabiao/github/KyClickHouse/build1/utils/local-engine/libch.so
5. ./build1/../contrib/llvm-project/libcxx/include/__utility/swap.h:37: DB::ActionsDAG::addFunctionImpl(std::__1::shared_ptr<DB::IFunctionBase const> const&, std::__1::vector<DB::ActionsDAG::Node const*, std::__1::allocator<DB::ActionsDAG::Node const*> >, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) @ 0x143e8c77 in /data3/liangjiabiao/github/KyClickHouse/build1/utils/local-engine/libch.so
```

Since `array` type is nullable in gluten,  the result from `groupArray` could be null now. But spark also require the result from `collect_list` non-nullable.

### PR DESCRIPTION
**Pull request by lgbo-ustc**
### Changelog category (leave one):
- Bug Fix

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

closed #398

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lgbo-ustc** [comment]
test this please with 1301

**Comment by liuneng1994** [comment]
test this please with 1301

**Comment by lgbo-ustc** [comment]
test this please with 1301

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
