### PR TITLE
[CH-278] part2: support xxhash64/hash

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
part2 of issue 278: support xxhash64/hash

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
test this please with 925

**Comment by taiyang-li** [comment]
test this please with 925

**Comment by taiyang-li** [comment]
test this please with 925

**Comment by taiyang-li** [comment]
test this please with 925

**Comment by liuneng1994** [comment]
test this please with 925

**Comment by taiyang-li** [comment]
test this please with 925

**Comment by taiyang-li** [comment]
test this please with 925

**Comment by taiyang-li** [comment]
test this please with 925

**Comment by taiyang-li** [comment]
test this please with 925

**Comment by taiyang-li** [comment]
test this please with 925

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
