### PR TITLE
[CH-215] Support shift left and shift right function. 

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support shift left and shift right function. 

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
Attention: it must be merge after https://github.com/oap-project/gluten/pull/606

**Comment by liuneng1994** [comment]
test this please

**Review by zzcclp — APPROVED** [review]
LGTM

**Pull request merged**
