### PR TITLE
[CH-120] Support memory manager

### PR DESCRIPTION
**Pull request by liuneng1994**
对接spark的内存管理

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by liuneng1994** [comment]
test please with 454

**Comment by liuneng1994** [comment]
test this please with 454

**Comment by liuneng1994** [comment]
test this please with 454

**Comment by zzcclp** [comment]
test this please with 454

**Comment by liuneng1994** [comment]
test this please with 454

**Pull request merged**
