### PR TITLE
[VL] Support Decimal type in Gluten

### PR DESCRIPTION
**Pull request by loneylee**
Velox resize checkoverflow function args to 3.
Fix it.

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by liuneng1994** [comment]
test this please

**Comment by loneylee** [comment]
test this please with 1176

**Review by jinchengchenghh — APPROVED** [review]

**Comment by loneylee** [comment]
test this please with 1176

**Comment by loneylee** [comment]
test this please with 1176

**Pull request merged**
