### PR TITLE
[CH-232] Support DataTypeNothing, which close https://github.com/Kyligence/ClickHouse/issues/232

### PR DESCRIPTION
**Pull request by taiyang-li**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Support DataTypeNothing, which close https://github.com/Kyligence/ClickHouse/issues/232

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by taiyang-li** [comment]
test this please with 791

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Comment by taiyang-li** [comment]
test this please with 791

**Comment by taiyang-li** [comment]
test this please with 791

**Pull request merged**
