### PR TITLE
Support repeat function

### PR DESCRIPTION
**Pull request by KevinyhZou**
Changelog category (leave one):
Support repeat function , as described in issue: https://github.com/Kyligence/ClickHouse/issues/297

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lgbo-ustc** [comment]
test this please

**Comment by KevinyhZou** [comment]
test this please with 975

**Comment by liuneng1994** [comment]
test this please with 975

**Comment by liuneng1994** [comment]
test this please with 975

**Comment by liuneng1994** [comment]
test this please with 975

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Pull request merged**
