### PR TITLE
[CH-353] ShuffleSplitter improvement

### PR DESCRIPTION
**Pull request by exmy**
### Changelog category (leave one):
- Improvement

see issue: [issue-353](https://github.com/Kyligence/ClickHouse/issues/353)

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by liuneng1994** [comment]
test this please with 1103

**Review by liuneng1994 — APPROVED** [review]
LGTM

**Comment by liuneng1994** [comment]
test this please with 1103

**Pull request merged**
