### PR TITLE
Update window function: lead, lag

### PR DESCRIPTION
**Pull request by lgbo-ustc**
Changelog category (leave one):
- New Feature

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

> Information about CI checks: https://clickhouse.tech/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

**Comment by lgbo-ustc** [comment]
test this please with 906

**Comment by lgbo-ustc** [comment]
test this please with 906

**Comment by liuneng1994** [comment]
@lgbo-ustc 代码冲突需要解决一下

**Comment by lgbo-ustc** [comment]
move to a new pr #322

**Pull request closed without merging**
